### ISSUE TITLE
Configurable Missing `var` Detection in Tests

### ISSUE THREAD

**Issue by kriskowal** [tlrobinson/narwhal#18]
Presently, the test runner asserts that the global object may not change during the course of a test.  Make this feature suppressible with a flag for all tests on a particular object or on a particular test, preferably in accordance with a ServerJS specification or proposal.

**Comment by kriskowal** [comment]
http://github.com/kriskowal/narwhal/commit/55eda57bebc81db62e283d721caf7715fc8fb22a

**Comment by smith** [comment]
This seems to work (tried it on Jaxer)

**Comment by kriskowal** [comment]
Good enough for me.
