### ISSUE TITLE
URI decoding

### ISSUE THREAD

**Issue by kriskowal** [tlrobinson/narwhal#2]
We need functions that can properly decode:

URI Components like paths.
URI Components in query strings (must decode + as space)
Query strings in general.
URI's in general.

**Comment by isaacs** [comment]
I added some more fancy query string decoding in Jack.  Should this perhaps be moved into Narwhal?

**Comment by kriskowal** [comment]
Yes, I think query parsing and formatting would be good to have in Narwhal proper.  There would be use for these things beyond application serving.  Let's get them into an experimental branch so we can organize the API.

**Comment by isaacs** [comment]
The query string decoding is moved over to Narwhal in my Jack and Narwhal forks.

I'm planning on implementing the suggestions in the discussion list about moving the request body handling to middleware and mirroring some of Rack's naming conventions.

Anyone have any strong feelings about uri.js vs url.js?  They seem like they're doing the same job.

**Comment by kriskowal** [comment]
Pretty sure we've done this.

**Comment by isaacs** [comment]
Yeah, we talked about this a month or two ago on IRC, iirc.

**Comment by kriskowal** [comment]
Closing.
