### ISSUE TITLE
Binary Stream `forEach`

### ISSUE THREAD

**Issue by kriskowal** [tlrobinson/narwhal#24]
Consider implementing `forEach` on Binary streams in terms of `read(null)` (for read up the the default buffer length and execute a block with the result).

**Comment by kriskowal** [comment]
This will permit byte streaming in Jack, improving performance for large files, and making it possible to stream files larger than the Jack app's active memory.

**Comment by kriskowal** [comment]
I'm pretty sure we've done this.

**Comment by kriskowal** [comment]
Closing

**Comment by tlrobinson** [comment]
This is only implemented on TextInputStream, not normal input streams. Shall we open a new issue for that? I don't think we can reopen closed issues.

**Comment by kriskowal** [comment]
Drat. I'll take care of it.
