### ISSUE TITLE
[rhino] Overwrite CLASSPATH, support NARWHAL_CLASSPATH

### ISSUE THREAD

**Issue by kriskowal** [tlrobinson/narwhal#31]
Users that have manually managed their CLASSPATH can run into problems when they have alternate versions of Narwhal's "jars".  At the moment, the Rhino bootstrapping process inherits the CLASSPATH environment and only augments it with its js.jar and jsline.jar.  To improve first impressions of Narwhal, we should overwrite CLASSPATH and inherit NARWHAL_CLASSPATH if a user has very deliberately asked for jars to be installed at bootstrapping time.  Package jars would still be loaded automatically with a dynamic class loader, obviating the need for NARWHAL_CLASSPATH in most cases.

**Comment by tlrobinson** [comment]
Implemented in http://github.com/tlrobinson/narwhal/commit/66472e7f8b7a7d93921b8ab870d8197df8dc19e2
