### ISSUE TITLE
warnings when starting local GAE server

### ISSUE THREAD

**Issue by rsaccon** [tlrobinson/narwhal#33]
This warnings should be surpressed on GAE:

```
 [java] The server is running at http://localhost:8080/ 
 [java] warning: couldn't install jar loader: JavaException: java.lang.IllegalArgumentException: Loader can not resolve Rhino classes 
```

**Comment by kriskowal** [comment]
If I'm not mistaken, this occurs when attempting to install a class loader in lib/packages.js as part of the bootstrapping process.

**Comment by kriskowal** [comment]
From Roberto on the mailing list: http://radomirmladenovic.info/2009/06/15/detecting-code-execution-on-google-app-engine

**Comment by kriskowal** [comment]
This should fix the problem http://github.com/kriskowal/narwhal/commit/c8b42579ecad46d0ee954ff529be49516bc4e664

Please verify and close, or let me know if the problem persists.

**Comment by kriskowal** [comment]
Verified by George Moschovitis.
