### ISSUE TITLE
args "natural()" (possible "validate") results in infinite loop

### ISSUE THREAD

**Issue by tlrobinson** [tlrobinson/narwhal#36]
To reproduce revert jackup's "-p" option to use "natural()" instead of "set()" and execute jackup with "-p 8081" etc.

**Comment by kriskowal** [comment]
http://github.com/kriskowal/narwhal/commit/a8c3a649de5a5e9c9dd8a9e9f48b11f2add282cd

**Comment by tlrobinson** [comment]
Yup, fixed. Sorry I forgot about this one.
