### ISSUE TITLE
forEach fixes

### ISSUE THREAD

**Issue by tschaub** [tlrobinson/narwhal#37]
If `Array.prototype.forEach` is not defined, the one provided by the default engine doesn't match the one described in ES5 15.4.4.18.  In addition, the `ByteArray.prototype.forEach` signature is one arg short.

I don't see a way to attach patches to these issues, so I've forked and sent a pull request.  Let me know you guys prefer a different way of doing things.

http://github.com/tschaub/narwhal/commit/2e13733e7585293523e57641f8cbc0d795bba6f2

Thanks.

**Comment by tlrobinson** [comment]
http://github.com/tlrobinson/narwhal/commit/2e13733e7585293523e57641f8cbc0d795bba6f2
