### ISSUE TITLE
More robust util::isArrayLike

### ISSUE THREAD

**Issue by cadorn** [tlrobinson/narwhal#38]
I had to patch the isArrayLike function as follows to get it working 
properly on xulrunner.

```
exports.isArrayLike = function(object) {
    return object &&
        typeof object === "object" &&
        (
            object.constructor === Array ||
            typeof object.callee !== "undefined" ||
            Object.prototype.toString.apply(object) === '[object Array]'
        );
};
```

The _Object.prototype.toString.apply(object) === '[object Array]'_ comes 
from Douglas Crockford's book JavaScript: The Good Parts.

**Comment by cadorn** [comment]
Commit: http://github.com/cadorn/narwhal/commit/a4e16ca597552e23668a3cacb94bc9eefdf6035d

**Comment by kriskowal** [comment]
Fixed.
