### ISSUE TITLE
tusk install broken

### ISSUE THREAD

**Issue by tschaub** [tlrobinson/narwhal#41]
Looks like something broke with 46f31ce5609120703d314466379fe5570f9e3db7.

```
narwhal$ rm -rf .tusk/
narwhal$ git checkout 72dfc8054febce04e6c4808fd43f4822b3d27159
HEAD is now at 72dfc80... Add 'xterm' to make term module work on Ubuntu/Gnome.
narwhal$ tusk install foo
Downloading catalog.
Saving catalog.
ERROR: Package not found: "foo"
No new packages to install.
narwhal$ rm -rf .tusk/
narwhal$ git checkout 46f31ce5609120703d314466379fe5570f9e3db7
Previous HEAD position was 72dfc80... Add 'xterm' to make term module work on Ubuntu/Gnome.
HEAD is now at 46f31ce... Added a Java version check to narwhal-rhino.
narwhal$ tusk install foo
tusk update does not yet take arguments.
```

I think I'm only seeing the problem when I don't have a .tusk directory.  I'm also going a little nuts so I may be missing something obvious.

**Comment by tschaub** [comment]
Ignore the GFM auto-linking in code blocks.

**Comment by tschaub** [comment]
Ok, perhaps this is my misread of the docs.  Things work if I `tusk update` before `tusk install`.

```
narwhal$ tusk install foo
tusk update does not yet take arguments.
narwhal$ tusk update
Downloading catalog.
Saving catalog.
narwhal$ tusk install foo
ERROR: Package not found: "foo"
No new packages to install.
```

Looks like this came with fd807971cc726c24569b8ec45f134f33d49e36b1.  Apologies for the chatter.

**Comment by kriskowal** [comment]
I introduced this bug.  It's because install calls the update action, and update checks to make sure that the user supplied no arguments.  The update task is reading the install arguments, which is not intended.  I will need to refactor.

**Comment by kriskowal** [comment]
Tom has reverted the commit that introduced this problem.  However, it would still be desirable for tusk update to verify that, when it is called by that name and not as a function of install, there are no args specified.

**Comment by kriskowal** [comment]
This has been fixed.
