### ISSUE TITLE
printing arrays is confusing

### ISSUE THREAD

**Issue by bryanwb** [tlrobinson/narwhal#49]
print("1,2,3".split(",") )
"1,2,3"
rather than
["1", "2", "3"]

it works as expected in that "1,2,3".split(",") [1]  gives me "2"  but the printed output is confusing

 but it prints the same output as 
print("1,2,3")   

In this way, narwhal behaves much differently than Firebug console or Web-Inspector console.

**Comment by tlrobinson** [comment]
There's nothing special going on, it's just using Array's toString method.

Maybe we should use util.repr() to print the results from on the command line.
