### ISSUE TITLE
s/platform/engine/

### ISSUE THREAD

**Issue by kriskowal** [tlrobinson/narwhal#5]
Rename platforms to the less ambiguous "engines", throughout the code, directory schema, and documentation.

**Comment by kriskowal** [comment]
Now in kriskowal/experimental with commit http://github.com/kriskowal/narwhal/commit/a18eaf5eb105fb5a93957e2950962a6aa3decbd7

Passes all unit tests on Mac OS X with Rhino.

**Comment by tlrobinson** [comment]
Merged in master. Closing.
