### ISSUE TITLE
Better regex for finding require()

### ISSUE THREAD

**Issue by dangoor** [tlrobinson/narwhal#52]
I had a problem where SC.require was being picked up by the dependency checking code. Here's a better regex:

http://github.com/dangoor/narwhal/commit/9e3b938f1b8200ef074d3a96ee4ff96ac706c588

**Comment by kriskowal** [comment]
This has been merged and is in my master.

**Comment by tlrobinson** [comment]
http://github.com/tlrobinson/narwhal/commit/42a30d224246fea0ee27e64de045c7beab620f22
