### ISSUE TITLE
ByteArray slice throws exception

### ISSUE THREAD

**Issue by Gozala** [tlrobinson/narwhal#53]

**Comment by Gozala** [comment]
Here is the fix for this one 
http://github.com/Gozala/narwhal/commit/e3ff8c3c839f3bddf179903ae49be8ce36997267

I have not managed to add a label not sure why :(

But I'm sending a pull request

**Comment by tlrobinson** [comment]
http://github.com/tlrobinson/narwhal/commit/be33bf0eea378d8d3b3c6580f5df8e8260793a4c
