### ISSUE TITLE
Rhino Engine Should Default to JS Version 1.7

### ISSUE THREAD

**Issue by nrstott** [tlrobinson/narwhal#57]
Mailing list thread:
http://groups.google.com/group/narwhaljs/browse_thread/thread/312e44da82944cb4

Fix is in this commit: http://github.com/nrstott/narwhal/commit/baeaf060173ed33648928869bf77a45bd624638f

**Comment by tlrobinson** [comment]
While we're at it we should try to solve the OpenJDK problem once and for all. I have yet to find a combination of Rhino and the -Xbootclasspath/p: option that works.

**Comment by nrstott** [comment]
Can we treat these as separate issues?  I'll open an issue about the OpenJDK problem.  Here it is: http://github.com/tlrobinson/narwhal/issues#issue/61

**Comment by kriskowal** [comment]
This has been merged; it's in my master.
