### ISSUE TITLE
Backslashes always interpreted as new lines in interactive interpreter

### ISSUE THREAD

**Issue by fitzgen** [tlrobinson/narwhal#65]
Example:

When I input this in to the interpreter

```
js> var str = "He said \"Hello World\"";
```

and hit enter, it gets twisted in to this:

```
js> var str = "He said 
"Hello World
"";
js: "<stdin>", line 5: unterminated string literal
js: var str = "He said 
js: ..................^
js> js: "<stdin>", line 6: unterminated string literal
js: "Hello World
js: ...........^
```

Using Narwhal w/ Rhino 1.7 release 3 PRERELEASE 2009 04 05.

Not sure if this is an issue with Rhino or Narwhal, but I thought I would create an issue either way on the off chance that nobody else has discovered this.

**Comment by tlrobinson** [comment]
This was a problem with the rlwrap args. Fixed with SHA: 28fa7c972675007421de70c3d082b72c311e503e

**Comment by fitzgen** [comment]
Thanks a lot!

**Comment by kriskowal** [comment]
Closing.
