### ISSUE TITLE
refined NARWHAL_DEBUGGER option in narwhal-rhino.cmd

### ISSUE THREAD

**Issue by nevilleburnell** [tlrobinson/narwhal#66]
http://github.com/cloudwork/narwhal/commit/c968c5f2d777b49e5f72507c98811572aa9f51b6

**Comment by tlrobinson** [comment]
SHA: b9546e9b5655f4b495beffea1aed7dcf44c4d5fe

**Comment by kriskowal** [comment]
Tom, can this be closed?

**Comment by tlrobinson** [comment]
I think so.
